name: Deploy Profile

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run deployment script
      run: |
        chmod +x ./deploy.sh
        ./deploy.sh
